[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
dioxus = { workspace = true, features = ["router", "fullstack"] }
server = { workspace = true }

[features]
default = []
#web = ["dioxus/web"]
desktop = ["dioxus/desktop"]
server = ["dioxus/server", "server/server"]

[dev-dependencies]
dioxus-cli = "0.7.2"
